### ISSUE TITLE
카테고리>진행상태 마우스 호버시 전체보기에 선택이 되어있지 않는 현상

### ISSUE THREAD

**Issue by kimhwanhoon** [kimhwanhoon/zombie-bucket-list#31]
카테고리 처음 로드시 전체보기인 상태인데 마우스 호버시에 시작전이 선택되어있는 현상

**Comment by HiYongA** [comment]
마우스 호버 시 전체보기로 기본 설정되게 수정 완료했습니다~!
수정 전 : defaultSelectedKeys: ['1'] -> 수정 후  : defaultSelectedKeys: ['0']
